# client/Dockerfile.dev
FROM node:25-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port Vite
EXPOSE 5173

# Commande par défaut (sera surchargée par docker-compose)
CMD ["npm", "run", "dev", "--", "--host"]